---
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
:url: <%= ENV.fetch('REDIS_WORKER_URL') { 'redis://localhost:6379/1' } %>
production:
  :concurrency: 10 # heroku free-tier limit: 10
:queues:
  - corpus
  - default
